    <?php
    $translations = [
        'welcome_message' => 'ようこそ！',
        'language_select' => '言語を選択',
        'save_button' => '保存',
        "search_placeholder"=> "すべてのアイテムから探す",
        "guest"=> "ゲスト",
        "user_name"=> "{{name}}さん",
        "brand_search_title"=> "ブランド検索",
        "filter_by_alphabet"=> "アルファベットで絞り込む",
        "all"=> "すべて",
        "alphabet_A"=> "A",
        "alphabet_B"=> "B",
        "alphabet_C"=> "C",
        "alphabet_D"=> "D",
        "alphabet_E"=> "E",
        "alphabet_F"=> "F",
        "alphabet_G"=> "G",
        "alphabet_H"=> "H",
        "alphabet_I"=> "I",
        "alphabet_J"=> "J",
        "alphabet_K"=> "K",
        "alphabet_L"=> "L",
        "alphabet_M"=> "M",
        "alphabet_N"=> "N",
        "alphabet_O"=> "O",
        "alphabet_P"=> "P",
        "alphabet_Q"=> "Q",
        "alphabet_R"=> "R",
        "alphabet_S"=> "S",
        "alphabet_T"=> "T",
        "alphabet_U"=> "U",
        "alphabet_V"=> "V",
        "alphabet_W"=> "W",
        "alphabet_X"=> "X",
        "alphabet_Y"=> "Y",
        "alphabet_Z"=> "Z",

        "keyword_label"=> "キーワード",
        "keyword_placeholder"=> "キーワードを入力",
        "gender_label"=> "性別",
        "men"=> "男性",
        "woman"=> "女性",
        "category_label"=> "カテゴリー",
        "all"=> "すべて",
        "subcategory_label"=> "サブカテゴリー",
        "price_range"=> "価格帯",
        "min_price_placeholder"=> "最小価格",
        "max_price_placeholder"=> "最大価格",
        "sale_label"=> "セール対象",
        "sale"=> "セール対象",
        "no_sale"=> "セールなし",
        "search_button"=> "検索",

        "cart"=> "カート",
        "🔔"=> "🔔",
        "login"=> "ログイン",
        "♡"=> "♡",
        "info"=> "登録情報",
        "order"=> "発注履歴・発送状況",
        "logout"=> "ログアウト",

        "search"=> "探す",
        "search_by_brand"=> "ブランドで探す",
        "search_by_category"=> "カテゴリ―で探す",
        "search_by_ranking"=> "ランキングで探す",
        "search_by_sale"=> "セール対象で探す",
        "search_by_diagnosis"=> "診断から探す",
        "advanced_search"=> "詳細検索",
        "categories_from"=> "カテゴリーから探す",
        "brand"=> "ブランド",
        "product_name"=> "商品名",
        "price"=> "値段",
        "discounted_price"=> "割引後価格",
        "description"=> "商品説明",
        "previous"=> "前へ",
        "next"=> "次へ",

            "tops" => "トップス",
            "tshirt-cutsew" => "tシャツ/カットソー",
            "shirt/blouse" => "シャツ/ブラウス",
            "polo-shirt" => "ポロシャツ",
            "knit/sweater" => "ニット/セーター",
            "vest" => "ベスト",
            "parka" => "パーカー",
            "sweat" => "スウェット",
            "cardigan" => "カーディガン",
            "bolero" => "ボレロ",
            "ensemble" => "アンサンブル",
            "jersey" => "ジャージ",
            "tanktop" => "タンクトップ",
            "camisole" => "キャミソール",
            "tubetop" => "チューブトップス",
            "other-tops" => "その他トップス",
        
            // ジャケット/アウター
            "jacket" => "ジャケット",
            "outerwear" => "アウター",
            "tailored-jacket" => "テーラードジャケット",
            "collarless-jacket" => "ノーカラージャケット",
            "collarless-coat" => "ノーカラーコート",
            "denim-jacket" => "デニムジャケット",
            "riders-jacket" => "ライダースジャケット",
            "blouson" => "ブルゾン",
            "military-jacket" => "ミリタリージャケット",
            "down-jacket" => "ダウンジャケット",
            "coat" => "コート",
            "down-vest" => "ダウンベスト",
            "duffle-coat" => "ダッフルコート",
            "trench-coat" => "トレンチコート",
            "nylon-jacket" => "ナイロンジャケット",
            "mods-coat" => "モッズコート",
            "other-outerwear" => "その他アウター",
        
            // パンツ
            "pants" => "パンツ",
            "denim-pants" => "デニムパンツ",
            "cargo-pants" => "カーゴパンツ",
            "chino-pants" => "チノパンツ",
            "sweat-pants" => "スウェットパンツ",
            "slacks" => "スラックス",
            "other-pants" => "その他パンツ",
        
            // スカート
            "skirt" => "スカート",
            "denim-skirt" => "デニムスカート",
        
            // ワンピース
            "onepiece" => "ワンピース",
            "shirt-onepiece" => "シャツワンピース",
            "jumper-skirt" => "ジャンパースカート",
            "tunic" => "チュニック",
            "dress" => "ドレス",
            "pants-dress" => "パンツドレス"
        
        
        
        
        ];
    ?>